import * as vscode from 'vscode';
import { resolveAIProvider } from '../ai';
import { ConsentManager } from '../config/consent';
import { SecretsStore } from '../config/secrets';
import { TaskRepository } from '../storage/taskRepository';
import { ContinuitySettings, TaskContext } from '../types';
import { ContinuityStatusBar } from '../ui/statusBar';

/** Minimum distinct files edited before we fire an AI naming call. */
const MIN_DISTINCT_FILES = 3;

/** Compact bundle sent to the naming model — file list + up to 3 diffs. */
function buildNamingBundle(ctx: TaskContext): string {
  const files = [...new Set(ctx.fileEdits.map(e => e.filePath))];
  const lines: string[] = [
    `Touched files: ${files.join(', ')}`,
    ''
  ];

  const shown = ctx.fileEdits.slice(-3);
  for (const edit of shown) {
    lines.push(`File: ${edit.filePath}`);
    lines.push('```diff');
    lines.push(edit.diff.trim().slice(0, 1500));
    lines.push('```');
    lines.push('');
  }

  return lines.join('\n');
}

export class BackgroundSessionNamer {
  /** Track which session IDs have already been AI-named so we fire only once. */
  private readonly namedSessions = new Set<string>();

  constructor(
    private readonly repository: TaskRepository,
    private readonly secrets: SecretsStore,
    private readonly consent: ConsentManager,
    private readonly settings: () => ContinuitySettings,
    private readonly statusBar: ContinuityStatusBar,
    private readonly output: vscode.OutputChannel
  ) {}

  /**
   * Called after each file flush. Checks whether there's enough signal and
   * Pro mode is active, then fires a background AI naming call if so.
   * Never throws — all errors are logged silently.
   */
  async maybeNameSession(): Promise<void> {
    try {
      await this.attempt();
    } catch (err) {
      this.output.appendLine(
        `Session naming skipped: ${err instanceof Error ? err.message : String(err)}`
      );
    }
  }

  private async attempt(): Promise<void> {
    const cfg = this.settings();
    if (cfg.offlineMode || !cfg.enrichHandoffWithAI) return;
    if (!this.consent.hasExtractionConsent()) return;

    const task = await this.repository.getActiveTask();
    if (!task) return;
    if (this.namedSessions.has(task.id)) return;

    const ctx = await this.repository.getTaskContext(task.id);
    if (!ctx) return;

    // Only fire once we have enough diffs to infer meaningful intent
    const distinctFiles = new Set(ctx.fileEdits.map(e => e.filePath)).size;
    if (distinctFiles < MIN_DISTINCT_FILES) return;

    // Only rename sessions that still have the auto-generated placeholder name
    const goalEvents = ctx.events.filter(e => e.type === 'goal');
    const isStillAutogenerated = goalEvents.length === 0 || goalEvents.every(e => {
      try { return JSON.parse(e.metadata ?? '{}').source === 'startTask'; } catch { return false; }
    });
    if (!isStillAutogenerated) return;

    const resolution = await resolveAIProvider(cfg, this.secrets);
    if (!resolution.provider) return;

    // Mark as named before the async call to prevent concurrent duplicate calls
    this.namedSessions.add(task.id);

    const bundle = buildNamingBundle(ctx);
    const { name, goal } = await resolution.provider.inferSessionName(bundle);

    await this.repository.renameTask(task.id, name);
    if (goal) {
      await this.repository.addEvent(task.id, 'goal', goal, { source: 'ai-named' });
    }

    this.statusBar.setActiveTask({ ...task, name });
    vscode.window.setStatusBarMessage(
      `$(sparkle) Continuity: session named "${name}"`,
      6_000
    );
    this.output.appendLine(`Session AI-named: "${name}" (${distinctFiles} files touched).`);
  }

  /** Call when a session is manually renamed — prevents AI from overwriting user intent. */
  lockSession(taskId: string): void {
    this.namedSessions.add(taskId);
  }
}
