import { FileEdit, PromptBuildOptions, TaskContext, TaskEvent } from '../types';

const DEFAULT_MAX_DIFFS_PER_FILE = 3;
const FREE_MODE_MAX_DIFFS_PER_FILE = 1;
const MAX_SNAPSHOTS = 3;
const FREE_MODE_MAX_LIST_ITEMS = 4;
const PRO_MODE_MAX_LIST_ITEMS = 6;
const MAX_DIFF_LINES_PER_EDIT = 6;
const MAX_DIFF_LINE_CHARS = 120;
const MAX_FILES_IN_DIFF_SECTION = 8;

export function buildHandoffPrompt(context: TaskContext, options: PromptBuildOptions): string {
  const isFreeMode = options.isFreeMode ?? true;
  const goal = latestEventContent(context.events, 'goal') ?? context.task.name;
  // A session is "auto-generated" if there are no goal events, or all goal events
  // came from the system (source: 'startTask'). User renames produce source: 'rename'.
  const isAutoGeneratedSession = isSystemGeneratedGoal(context.events);
  const decisions = eventContents(context.events, 'decision');
  const assumptions = eventContents(context.events, 'assumption');
  const pending = eventContents(context.events, 'pending');
  const snapshots = eventContents(context.events, 'snapshot').slice(-MAX_SNAPSHOTS);
  const touchedFiles = unique(context.fileEdits.map((edit) => edit.filePath)).sort();
  const lastActivity = latestTimestamp(context);
  const maxListItems = isFreeMode ? FREE_MODE_MAX_LIST_ITEMS : PRO_MODE_MAX_LIST_ITEMS;

  const taskName = isFreeMode && isAutoGeneratedSession
    ? deriveSmartSessionName(context.fileEdits)
    : context.task.name;

  const sections = [
    '[CAMS Handoff]',
    `Target assistant: ${options.targetAssistant ?? 'Generic Assistant'}`,
    `Task: ${taskName}`,
    !isAutoGeneratedSession || goal !== context.task.name ? `Goal: ${goal}` : null,
    lastActivity ? `Last activity: ${humanizeTimestamp(lastActivity)}` : null,
    ''
  ];

  const hasStructuredContent = pending.length > 0 || decisions.length > 0 || assumptions.length > 0 || snapshots.length > 0;
  const hasDiffs = context.fileEdits.length > 0;

  if (!hasStructuredContent && !hasDiffs) {
    sections.push('(Free tier handoff — nothing captured yet. Edit some files or save a snapshot to populate this.)');
  } else {
    if (pending.length > 0) sections.push(formatList('Pending', pending, maxListItems));
    if (decisions.length > 0) sections.push(formatList('Decisions made', decisions, maxListItems));
    if (assumptions.length > 0) sections.push(formatList('Assumptions', assumptions, maxListItems));
    if (touchedFiles.length > 0) sections.push(formatTouchedFiles(touchedFiles, isFreeMode));
    if (snapshots.length > 0) sections.push(formatSnapshots(snapshots, maxListItems));
    if (hasDiffs) sections.push(formatDiffs(context.fileEdits, isFreeMode));
    if (isFreeMode && !hasStructuredContent) {
      sections.push('(Free mode — save a snapshot or run "CAMS: Configure AI" to enrich with AI-inferred decisions and pending items.)');
    }
  }

  const footerSections = [];
  if (decisions.length > 0 || assumptions.length > 0 || pending.length > 0) {
    footerSections.push('Continue from here. Preserve the existing decisions, call out uncertainty, and focus on the pending work.');
  } else {
    footerSections.push('Continue from here. Recent diffs above are the only authoritative record — assume nothing else.');
  }
  sections.push(footerSections.join(''));

  return enforceBudget(sections.filter(Boolean).join('\n'), options.maxChars);
}

function eventContents(events: TaskEvent[], type: TaskEvent['type']): string[] {
  return events.filter((event) => event.type === type).map((event) => event.content.trim()).filter(Boolean);
}

function latestEventContent(events: TaskEvent[], type: TaskEvent['type']): string | undefined {
  return eventContents(events, type).at(-1);
}

function latestTimestamp(context: TaskContext): string | undefined {
  const timestamps = [
    context.task.updatedAt,
    ...context.events.map((event) => event.timestamp),
    ...context.fileEdits.map((edit) => edit.timestamp)
  ].filter(Boolean);
  return timestamps.sort().at(-1);
}

function formatList(title: string, items: string[], maxItems: number): string {
  if (items.length === 0) {
    return `${title}:\n- None captured.`;
  }
  const limited = items.slice(-maxItems);
  const extraCount = Math.max(0, items.length - limited.length);
  const lines = limited.map((item) => `- ${singleLine(item)}`);
  if (extraCount > 0) {
    lines.push(`- (+${extraCount} older item${extraCount === 1 ? '' : 's'})`);
  }
  return `${title}:\n${lines.join('\n')}`;
}

function formatTouchedFiles(files: string[], isFreeMode: boolean): string {
  if (files.length === 0) return '';
  const topic = computeFileTopic(files);
  return `Scope: ${topic}`;
}

function formatSnapshots(snapshots: string[], maxItems: number): string {
  if (snapshots.length === 0) return '';

  const limited = snapshots.slice(-maxItems);
  const extraCount = Math.max(0, snapshots.length - limited.length);
  const lines = limited.map((snapshot) => `- ${truncate(singleLine(snapshot), 180)}`);
  if (extraCount > 0) {
    lines.push(`- (+${extraCount} older snapshot${extraCount === 1 ? '' : 's'})`);
  }
  return `Recent chat snapshots:\n${lines.join('\n')}`;
}

function formatDiffs(fileEdits: FileEdit[], isFreeMode: boolean = true): string {
  if (fileEdits.length === 0) return '';

  const grouped = new Map<string, FileEdit[]>();
  for (const edit of fileEdits) {
    const edits = grouped.get(edit.filePath) ?? [];
    edits.push(edit);
    grouped.set(edit.filePath, edits);
  }

  const maxPerFile = isFreeMode ? FREE_MODE_MAX_DIFFS_PER_FILE : DEFAULT_MAX_DIFFS_PER_FILE;
  const allFiles = [...grouped.entries()].sort(([a], [b]) => a.localeCompare(b));
  const files = allFiles.slice(0, MAX_FILES_IN_DIFF_SECTION);
  const sections: string[] = ['Recent file changes:'];
  for (const [filePath, edits] of files) {
    sections.push(`\nFile: ${filePath}`);
    for (const edit of edits.slice(-maxPerFile)) {
      const compact = compactDiff(edit.diff);
      if (!compact) continue;
      sections.push(compact);
    }
  }
  const hiddenFiles = allFiles.length - files.length;
  if (hiddenFiles > 0) {
    sections.push(`\n(+${hiddenFiles} additional file${hiddenFiles === 1 ? '' : 's'} not shown)`);
  }
  return sections.join('\n');
}

function singleLine(value: string): string {
  return value.replace(/\s+/g, ' ').trim();
}

function truncate(value: string, maxChars: number): string {
  if (value.length <= maxChars) return value;
  return `${value.slice(0, Math.max(0, maxChars - 1))}…`;
}

function compactDiff(diff: string): string {
  const lines = diff.split('\n');
  const picked: string[] = [];

  for (const line of lines) {
    if (!(line.startsWith('+') || line.startsWith('-'))) continue;
    if (
      line.startsWith('+++') ||
      line.startsWith('---') ||
      line.startsWith('++++') ||
      line.startsWith('----')
    ) {
      continue;
    }
    picked.push(truncate(line, MAX_DIFF_LINE_CHARS));
    if (picked.length >= MAX_DIFF_LINES_PER_EDIT) break;
  }

  if (picked.length === 0) {
    return '- (structural/context edits captured; no concise line-level snippet available)';
  }

  return picked.map((line) => `- ${line}`).join('\n');
}

function unique(values: string[]): string[] {
  return [...new Set(values)];
}

function enforceBudget(prompt: string, maxChars: number): string {
  if (prompt.length <= maxChars) {
    return prompt;
  }

  const marker = '\n\n[CAMS truncated older context to fit the configured prompt budget.]';
  return `${prompt.slice(0, Math.max(0, maxChars - marker.length))}${marker}`;
}

function isSystemGeneratedGoal(events: TaskEvent[]): boolean {
  const goalEvents = events.filter(e => e.type === 'goal');
  if (goalEvents.length === 0) return true;
  return goalEvents.every(e => {
    try {
      return JSON.parse(e.metadata ?? '{}').source === 'startTask';
    } catch {
      return false;
    }
  });
}

function deriveSmartSessionName(fileEdits: FileEdit[]): string {
  if (fileEdits.length === 0) return 'Session (no diffs yet)';

  // Count edits per 2-level directory (e.g. "src/ai", "src/commands")
  const dirCount = new Map<string, number>();
  for (const edit of fileEdits) {
    const parts = edit.filePath.split('/');
    const dir = parts.length >= 3
      ? `${parts[0]}/${parts[1]}`
      : parts.length === 2
        ? parts[0]
        : null;
    if (dir) dirCount.set(dir, (dirCount.get(dir) ?? 0) + 1);
  }

  if (dirCount.size === 0) return 'root (auto)';

  const top2 = Array.from(dirCount.entries())
    .sort((a, b) => b[1] - a[1])
    .slice(0, 2)
    .map(([dir]) => dir);

  return `${top2.join(', ')} (auto)`;
}

function humanizeTimestamp(isoString: string): string {
  try {
    const date = new Date(isoString);
    const now = new Date();
    const diffMs = now.getTime() - date.getTime();
    const diffMins = Math.floor(diffMs / 60000);

    if (diffMins < 1) return `${date.toISOString().slice(0, 16).replace('T', ' ')} (now)`;
    if (diffMins < 60) return `${date.toISOString().slice(0, 16).replace('T', ' ')} (${diffMins}m ago)`;

    const diffHours = Math.floor(diffMins / 60);
    if (diffHours < 24) return `${date.toISOString().slice(0, 16).replace('T', ' ')} (${diffHours}h ago)`;

    const diffDays = Math.floor(diffHours / 24);
    return `${date.toISOString().slice(0, 16).replace('T', ' ')} (${diffDays}d ago)`;
  } catch {
    return isoString;
  }
}

function computeFileTopic(files: string[]): string {
  if (files.length === 0) return '0 files';

  const langs = new Map<string, number>();
  const dirs = new Set<string>();

  for (const file of files) {
    const parts = file.split('/');
    if (parts.length > 1) {
      dirs.add(parts[0]);
    }

    const ext = file.split('.').pop() ?? '';
    const lang = extToLang(ext);
    langs.set(lang, (langs.get(lang) ?? 0) + 1);
  }

  const dominantLang = Array.from(langs.entries()).sort((a, b) => b[1] - a[1])[0]?.[0] ?? 'file';
  const dirList = Array.from(dirs).sort().slice(0, 2);
  const dirStr = dirList.length > 0 ? `, mostly ${dirList.join(', ')}` : '';

  return `${files.length} ${dominantLang} files${dirStr}`;
}

function extToLang(ext: string): string {
  const map: Record<string, string> = {
    ts: 'TypeScript',
    tsx: 'TypeScript',
    js: 'JavaScript',
    jsx: 'JavaScript',
    py: 'Python',
    go: 'Go',
    rs: 'Rust',
    java: 'Java',
    cpp: 'C++',
    c: 'C',
    cs: 'C#',
    rb: 'Ruby',
    php: 'PHP',
    md: 'Markdown',
    json: 'JSON',
    yaml: 'YAML',
    yml: 'YAML',
    html: 'HTML',
    css: 'CSS'
  };
  return map[ext] ?? 'file';
}
